USE [master]
GO

/****** Object:  Database [MyDataBase]    Script Date: 11-08-2017 14:35:49 ******/
CREATE DATABASE [MyDataBase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MyDataBase', FILENAME = N'D:\MyWork\DatabaseFile\MyDataBase.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MyDataBase_log', FILENAME = N'D:\MyWork\DatabaseFile\MyDataBase_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [MyDataBase] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MyDataBase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MyDataBase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MyDataBase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MyDataBase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MyDataBase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MyDataBase] SET ARITHABORT OFF 
GO

ALTER DATABASE [MyDataBase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MyDataBase] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [MyDataBase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MyDataBase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MyDataBase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MyDataBase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MyDataBase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MyDataBase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MyDataBase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MyDataBase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MyDataBase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MyDataBase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MyDataBase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MyDataBase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MyDataBase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MyDataBase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MyDataBase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MyDataBase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MyDataBase] SET RECOVERY FULL 
GO

ALTER DATABASE [MyDataBase] SET  MULTI_USER 
GO

ALTER DATABASE [MyDataBase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MyDataBase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MyDataBase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MyDataBase] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [MyDataBase] SET  READ_WRITE 
GO


