USE [master]
GO

/****** Object:  Database [MyCalculator]    Script Date: 11-08-2017 16:20:47 ******/
CREATE DATABASE [MyCalculator]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MyCalculator', FILENAME = N'D:\MyWork\RND_Project\MyCalculator\DatabaseFile\MyCalculator.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MyCalculator_log', FILENAME = N'D:\MyWork\RND_Project\MyCalculator\DatabaseFile\MyCalculator_log.ldf' , SIZE = 3456KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [MyCalculator] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MyCalculator].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MyCalculator] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MyCalculator] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MyCalculator] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MyCalculator] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MyCalculator] SET ARITHABORT OFF 
GO

ALTER DATABASE [MyCalculator] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MyCalculator] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [MyCalculator] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MyCalculator] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MyCalculator] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MyCalculator] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MyCalculator] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MyCalculator] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MyCalculator] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MyCalculator] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MyCalculator] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MyCalculator] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MyCalculator] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MyCalculator] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MyCalculator] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MyCalculator] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MyCalculator] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MyCalculator] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MyCalculator] SET RECOVERY FULL 
GO

ALTER DATABASE [MyCalculator] SET  MULTI_USER 
GO

ALTER DATABASE [MyCalculator] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MyCalculator] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MyCalculator] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MyCalculator] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [MyCalculator] SET  READ_WRITE 
GO


